# docker-compose.yml
version: "2.3"
services:
    _RADIOLAB_DOCKER:
        image: _IMAGE
        container_name: _RADIOLAB_DOCKER
        runtime: nvidia
        shm_size: 512M
        user: _CURRENT_ID
        working_dir: /DATA
        stdin_open: true
        environment:
            - HOME=_HOME_docker
            - LIBGL_ALWAYS_INDIRECT=0
            - NVIDIA_VISIBLE_DEVICES=all
            - DISPLAY=host.docker.internal:0.0
            - USER=_USER
#        network_mode: "host"
        ports:
            - _PORT:8888
        volumes:
            - _HOME_local:_HOME_docker
            - _DATA:/DATA
            - _FS_LICENSE:/opt/freesurfer/license.txt
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ../group:/etc/group:ro
            - ../passwd:/etc/passwd:ro
        tty: true