# docker-compose.yml
version: "2.3"
services:
    {RADIOLAB_DOCKER}:
        image: {IMAGE}
        container_name: {RADIOLAB_DOCKER}
        shm_size: 512M
        user: {UID}:{GID}
        working_dir: /DATA
        stdin_open: true
        environment:
            - HOME={HOME}
            - LIBGL_ALWAYS_INDIRECT=0
            - DISPLAY=:80.0
            - USER={USER}
        ports:
            - {PORT}:8888
        volumes:
            - {HOME}:{HOME}
            - {MOUNT}:/DATA
{FS}            - {FS_LICENSE}:/opt/freesurfer/license.txt
            - radiolab_xpra_X11:/tmp/.X11-unix:rw
            - ../group:/etc/group:ro
            - ../passwd:/etc/passwd:ro
        tty: true

    radiolab_xpra:
        image: radiolab_xpra
        container_name: {RADIOLAB_DOCKER}_xpra
        shm_size: 512M
        stdin_open: true
        environment:
            - DISPLAY=:80.0
        ports:
            - 8080:8080
        volumes:
            - radiolab_xpra_X11:/tmp/.X11-unix:rw
        tty: true

volumes:
  radiolab_xpra_X11:
    external: true