# docker-compose.yml
version: "2.3"
services:
    radiolab_xpra:
        image: radiolab_xpra
        container_name: radiolab_xpra
        shm_size: 512M
        stdin_open: true
        environment:
            - DISPLAY=:80.0
        ports:
            - 8080:8080
        volumes:
            - radiolab_xpra_X11:/tmp/.X11-unix:rw
        tty: true

volumes:
  radiolab_xpra_X11:
    external: true